title: ValuCompass Experts
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

just_the_docs:
  color_scheme: light

permalink: pretty

defaults:
  - scope:
      path: ""      # everything under /docs (your build root)
      type: "pages"
    values:
      layout: "default"

collections:
  experts:
    output: true
    permalink: /experts/:name/

search_enabled: true

url: https://discovervalucompass.github.io
baseurl: /experts

footer_content: '© ValuCompass Experts'

logo: /assets/images/vc_experts_logo.png

#adding kramdown-parser to enable admonitions
callouts_level: quiet
callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: red
